---
- name: Upgrade pip
  pip: name=pip state=latest

- name: Upgrade setuptools
  pip: name=setuptools state=latest

- name: Install FlexGet
  pip: name=flexget state=latest

- name: Run FlexGet every 30 minutes with Cron
  cron:
    name: flexget
    minute: "*/30"
    job: "/usr/local/bin/flexget --cron execute"
    state: absent

- name: Create configuration directory
  file: path=/etc/flexget owner={{ media_user }} group={{ media_group }} state=directory recurse=yes

- name: Create Flexget configuration file
  copy: src=files/flexget-config.yml dest=/etc/flexget/config.yml owner={{ media_user }} group={{ media_group }}

- name: Create systemd service definition
  template: src=flexget.service.j2 dest=/usr/lib/systemd/system/flexget.service owner=root group=root

- name: Enable and start FlexGet service
  service: name=flexget enabled=yes state=started
