plex_download: https://downloads.plex.tv/plex-media-server/1.6.1.3722-4955e31cf/plexmediaserver_1.6.1.3722-4955e31cf_amd64.deb
plex_sha_checksum: 2b2a109654a1f0e2fc2fa5381403ce4f1931c7c2
plex_package_path: /tmp/plexmediaserver_1.6.1.3722-4955e31cf_amd64.deb
plex_application_support_dir: "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server"
