plex_download: https://downloads.plex.tv/plex-media-server/1.4.3.3433-03e4cfa35/plexmediaserver_1.4.3.3433-03e4cfa35_amd64.deb
plex_package_path: /tmp/plexmediaserver_1.4.3.3433-03e4cfa35_amd64.deb
plex_application_support_dir: "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server"
