---
# Installation
- name: Download plex
  get_url: url={{ plex_download }} dest={{ plex_package_path }}
  ignore_errors: yes
- name: Check if Plex is installed
  command: "dpkg -s plexmediaserver"
  register: result
  changed_when: False
  ignore_errors: yes
- name: Install Plex
  command: "dpkg -i {{ plex_package_path }}"
  when: result|failed

# Make sure Plex is started
- name: Ensure plex is running
  service: name=plexmediaserver state=started
