---
- name: Display Ansible distribution
  debug:
    msg: "{{ ansible_distribution }}"

# Variables
- include_vars: "{{ item }}"
  with_first_found:
  - "vars/{{ ansible_distribution }}.yml"
  when: plex_download is not defined or plex_path is not defined

- name: Install Plex on Fedora
  dnf: name={{ plex_download }} state=present
  when: ansible_distribution == 'Fedora'

- name: Install Plex on Ubuntu
  apt: deb={{ plex_download }} state=present
  when: ansible_distribution == 'Ubuntu'

- name: Ensure plex is running
  service: name=plexmediaserver state=started
