---
# Variables
- include_vars: "{{ item }}"
  with_first_found:
  - "vars/{{ ansible_distribution }}.yml"
  when: plex_download is not defined or plex_path is not defined

- name: Install Plex on Fedora
  dnf: name={{ plex_download }} state=present
  when: ansible_distribution == 'Fedora'

- name: Install Plex on Ubuntu
  apt: deb={{ plex_download }} state=present
  when: ansible_distribution == 'Ubuntu'

- name: Ensure that Plex user home directory exists
  file: path=/home/{{ media_user }} state=directory owner={{ media_user }} group={{ media_group }}

- name: Ensure that Plex Downloads directory exists
  file: path=/home/{{ media_user }}/Downloads state=directory owner={{ media_user }} group={{ media_group }}

- name: Ensure that Plex TV directory exists
  file: path=/home/{{ media_user }}/TV state=directory owner={{ media_user }} group={{ media_group }}

- name: Ensure that Plex Movies directory exists
  file: path=/home/{{ media_user }}/Movies state=directory owner={{ media_user }} group={{ media_group }}

- name: Ensure plex is running
  service: name=plexmediaserver state=restarted
