---
# Dependencies
- name: Ensure Plex dependencies are satisfied
  package: name={{ item }} state=present
  with_items:
  - libavahi-common3
  - libavahi-core7
  - libdaemon0
  - libnss-mdns
  - libavahi-client3
  - libavahi-common3
  - avahi-daemon
  - avahi-utils

# Installation
- name: Download plex .deb
  get_url: url={{ plex_download }} dest={{ plex_deb_path }} checksum={{ plex_sha_checksum }}
  ignore_errors: yes
- name: Check if plex is installed
  command: "dpkg -s plexmediaserver"
  register: result
  changed_when: False
  ignore_errors: yes
- name: Installing plex
  command: "dpkg -i {{ plex_deb_path }}"
  when: result|failed

# Make sure Plex is started
- name: Ensure plex is running
  service: name=plexmediaserver state=started
